= Shipilev's Quark #5: Heap Parsability

https://shipilev.net/jvm/anatomy-quarks/5-tlabs-and-heap-parsability/

== To run

[source,shell script]
----
mvn clean package
mvn exec:exec
----

== Short recap

There are run 300 threads which each of them allocates one object.
This allocation means to get a TLAB space and for heap to be parsable
the rest of the TLAB is filled with an `int[]`.

The other thread just makes the OOM to happen which in combination with `-XX:+HeapDumpOnOutOfMemoryError`
gives us the heap dump that we can https://www.eclipse.org/mat/[analyze].

[source,shell script]
----
# to get the dump being parsed
./mat/ParseHeapDump.sh java_pid50981.hprof
# to open memory analyzer and see the view
./mat/MemoryAnalyzer
# 'Open a Heap Dump' java_pid50981.hprof
----

[NOTE]
====
----
An internal error occurred during: "Parsing heap dump from 'java_pid50981.hprof'".
Java heap space
----

* Change the `./mat/MemoryAnalyzer.ini` to use more memory with e.g. `-Xmx4g`
* Add vm args at command line `-vmargs -Xmx4g -XX:-UseGCOverheadLimit`
====

== On program arguments

There is used the Epsilon GC to be predictable and 1GB heap to fail with OOM soon.

[source,shell script]
----
-Xmx1G -Xms1G -XX:+UnlockExperimentalVMOptions -XX:+UseEpsilonGC -XX:+HeapDumpOnOutOfMemoryError
----

NOTE: Use JDK11 or later.

To have the fixed TLAB don't permit resize TLAB and set the size
`-XX:TLABSize=1000000 -XX:-ResizeTLAB`.

== Observation

I cannot see the `int[]` in the used MAT (v. 1.10.0). It could be that it hides it as it knows
they're only filler data and it may be discarded from the user view.

Second thing is that I'm not able to find how to make EclipseGC to use fixed TLAB sizes.
The option `-XX:EpsilonTLABSize` seems not being available.

NOTE: heap Object allocation in JDK8, sources https://github.com/openjdk/jdk/blob/jdk8-b119/hotspot/src/share/vm/gc_interface/collectedHeap.cpp#L425